export const MOVIES_FETCH = 'MOVIES_FETCH';
export const MOVIES_FILTERING = 'MOVIES_FILTERING';
export const MOVIES_SORTING = 'MOVIES_SORTING';
export const MOVIES_SEARCH = 'MOVIES_SEARCH';
export const MOVIE_SELECTION = 'MOVIE_SElECTION';
export const MOVIES_REMOVING= 'MOVIES_REMOVING';
